version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=src/main.py
      - FLASK_ENV=development
    restart: unless-stopped
    # Uncomment and modify the following if you need to add a database later
    # depends_on:
    #   - db

  # Example database service (PostgreSQL) - uncomment and configure as needed
  # db:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_USER: your_user
  #     POSTGRES_PASSWORD: your_password
  #     POSTGRES_DB: kenyan_id_validator
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   ports:
  #     - "5432:5432"

# Uncomment if using the database service
# volumes:
#   postgres_data:
