version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: id-validation-app
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src
      - ./data:/app/data  # For persistent storage of uploaded files
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    # Uncomment the following lines if you need to use GPU
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
